/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fred_test_nativeTest_MyNative */

#ifndef _Included_fred_test_nativeTest_MyNative
#define _Included_fred_test_nativeTest_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fred_test_nativeTest_MyNative
 * Method:    showParams0
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_fred_test_nativeTest_MyNative_showParams0
  (JNIEnv *, jobject, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
